### ISSUE TITLE
Change link to the e-learning resources

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/developer-website#14]
To ensure that visitors land at the start of the e-learning resources, please change the [link](https://github.com/opengeospatial/developer-website/blob/4abcb14391e481b0435f153f41a5c855cf9443b6/src/pug/index.pug#L383) of the e-learning resources to https://opengeospatial.github.io/e-learning/index.html

**Comment by doublebyte1** [comment]
@ghobona https://github.com/opengeospatial/developer-website/commit/4d8d0b2f83f1695a687e78757619eb6b87d0ec9e
